#!/bin/bash
cp install ../; cd .. ; chmod +x install; clear;
echo -e "\033[1;34mAdding Universe APT repository to Ubuntu, insert your password:\033[0m";
sudo add-apt-repository universe -y > /dev/null;
echo -e "\033[1;35mUpdating Ubuntu...\033[0m";
sudo apt-get update > /dev/null 2>&1;
sudo apt-get upgrade -y > /dev/null 2>&1;
echo -e "\033[0;37mInstalling build-essential...\033[0m";
sudo apt install build-essential -y > /dev/null 2>&1;
mkdir webui; cd webui;
echo -e "\033[0;37mInstalling Aria2 (to download model)...\033[0m";
sudo apt-get install aria2 -y > /dev/null;
echo -e "\033[1;32mDownloading Miniconda ...\033[0m";
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh > /dev/null 2>&1;
echo -e "\033[1;34mAll done, you can close this window now ...\033[0m"
